CREATE TABLE match_participants
(
    match_id                        VARCHAR(20)  NOT NULL COMMENT 'Riot 매치 ID (matches.match_id 참조)',
    puuid                           VARCHAR(78)  NOT NULL COMMENT '참가자 PUUID',
    win                             TINYINT(1)   NOT NULL COMMENT '승리 여부 (1=승, 0=패)',
    kills                           INT          NOT NULL COMMENT '킬 수',
    deaths                          INT          NOT NULL COMMENT '데스 수',
    assists                         INT          NOT NULL COMMENT '어시스트 수',
    champion_id                     INT          NOT NULL COMMENT '사용 챔피언 ID',
    champion_name                   VARCHAR(50)  NOT NULL COMMENT '사용 챔피언 이름',
    queue_id                        INT          NOT NULL COMMENT '큐 ID (matches.queue_id 와 동일)',
    game_start                      BIGINT       NOT NULL COMMENT '게임 시작 시각 (Unix epoch ms)',
    team_position                   VARCHAR(10)  NULL     COMMENT '포지션 (TOP/JUNGLE/MID/BOTTOM/UTILITY)',
    total_minions_killed            INT          NOT NULL DEFAULT 0 COMMENT '미니언 처치 수',
    neutral_minions_killed          INT          NOT NULL DEFAULT 0 COMMENT '중립 몬스터 처치 수',
    game_duration                   INT          NOT NULL DEFAULT 0 COMMENT '게임 시간 (초)',
    total_damage_dealt_to_champions INT          NOT NULL DEFAULT 0 COMMENT '챔피언에게 가한 총 피해량',
    vision_score                    INT          NOT NULL DEFAULT 0 COMMENT '비전 점수',
    wards_placed                    INT          NOT NULL DEFAULT 0 COMMENT '설치한 와드 수',
    wards_killed                    INT          NOT NULL DEFAULT 0 COMMENT '제거한 와드 수',
    double_kills                    INT          NOT NULL DEFAULT 0 COMMENT '더블킬 횟수',
    triple_kills                    INT          NOT NULL DEFAULT 0 COMMENT '트리플킬 횟수',
    quadra_kills                    INT          NOT NULL DEFAULT 0 COMMENT '쿼드라킬 횟수',
    penta_kills                     INT          NOT NULL DEFAULT 0 COMMENT '펜타킬 횟수',
    PRIMARY KEY (match_id, puuid),
    INDEX idx_puuid_game_start (puuid, game_start)
) COMMENT = '매치 참가자별 파싱된 통계';
